-- ORUM continuity capsule · critical append-only verification schema
-- Safe to apply to a fresh PostgreSQL/Supabase database.

create table if not exists public.ora_verificacao_historico (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null,
  verifier text not null,
  verdict text not null check (verdict in ('VIVO', 'VIVO_COM_TRABALHO', 'OBSERVAR')),
  snapshot_sha256 text not null check (snapshot_sha256 ~ '^[0-9a-f]{64}$'),
  previous_record_sha256 text null check (previous_record_sha256 is null or previous_record_sha256 ~ '^[0-9a-f]{64}$'),
  record_sha256 text not null unique check (record_sha256 ~ '^[0-9a-f]{64}$'),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists ora_verificacao_historico_observed_at_idx
  on public.ora_verificacao_historico (observed_at desc, id desc);

alter table public.ora_verificacao_historico enable row level security;
revoke all on table public.ora_verificacao_historico from anon, authenticated;
grant select, insert on table public.ora_verificacao_historico to service_role;
revoke update, delete, truncate on table public.ora_verificacao_historico from service_role;
grant usage, select on sequence public.ora_verificacao_historico_id_seq to service_role;

create or replace function public.ora_verificacao_historico_immutable()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'ora_verificacao_historico is append-only';
end;
$$;

revoke all on function public.ora_verificacao_historico_immutable() from public, anon, authenticated;
grant execute on function public.ora_verificacao_historico_immutable() to service_role;

drop trigger if exists ora_verificacao_historico_block_mutation on public.ora_verificacao_historico;
create trigger ora_verificacao_historico_block_mutation
before update or delete on public.ora_verificacao_historico
for each row execute function public.ora_verificacao_historico_immutable();

drop policy if exists ora_verificacao_historico_service_read on public.ora_verificacao_historico;
create policy ora_verificacao_historico_service_read
on public.ora_verificacao_historico for select to service_role using (true);

drop policy if exists ora_verificacao_historico_service_insert on public.ora_verificacao_historico;
create policy ora_verificacao_historico_service_insert
on public.ora_verificacao_historico for insert to service_role with check (true);
