// ORA · openapi.json — catalogo de licenciamento 0001sensations (v2.2)
const GATEWAY = 'https://ora-x402-gateway.vercel.app';
function xPaymentHeaderParam() { return { name: 'X-PAYMENT', in: 'header', required: false, description: 'Prova de pagamento x402.', schema: { type: 'string', minLength: 8 } }; }
function obraParam() { return { name: 'obra', in: 'query', required: true, description: 'Titulo ou ID da obra 0001sensations a licenciar.', schema: { type: 'string', minLength: 1, maxLength: 200, default: 'presenca', examples: ['presenca', 'valium'] }, example: 'presenca' }; }
function resp402(desc) { return { description: desc, headers: { 'PAYMENT-REQUIRED': { description: 'PaymentRequired canonico x402 v2 (JSON base64).', schema: { type: 'string' } } }, content: { 'application/json': { schema: { type: 'object', properties: { x402Version: { type: 'integer' }, error: { type: 'string' }, accepts: { type: 'array', items: { type: 'object' } } } } } } }; }
function resp200() { return { description: 'Licenca emitida', content: { 'application/json': { schema: { type: 'object', required: ['acesso', 'licenca'], properties: { acesso: { type: 'string' }, licenca: { type: 'object' } } } } } }; }
function op(id, summary, priceUsd, withObra) { const o = { operationId: id, summary, tags: ['Licenciamento'], 'x-payment-info': { price: { mode: 'fixed', currency: 'USD', amount: priceUsd }, protocols: [{ x402: {} }] }, responses: { '200': resp200(), '402': resp402('Payment Required.') } }; if (withObra) o.parameters = [obraParam()]; return { get: o }; }
const DOC = { openapi: '3.1.0', info: { title: '0001sensations · Licenciamento de Arte via x402', version: '2.2.0', description: 'Licenciamento directo de obras originais 0001sensations.', contact: { email: 'jasm43@gmail.com' } }, servers: [{ url: GATEWAY }], paths: { '/licenca/preview': op('getLicencaPreview', '0001sensations · Licenca Preview', '1.618', true), '/licenca/editorial': op('getLicencaEditorial', '0001sensations · Licenca Editorial', '16.18', true), '/licenca/treino': op('getLicencaTreino', '0001sensations · Licenca de Treino IA', '161.80', true), '/licenca/arquivo': op('getLicencaArquivo', '0001sensations · Arquivo completo', '10000.00', true) } };
module.exports = (req, res) => { res.setHeader('content-type', 'application/json; charset=utf-8'); res.setHeader('access-control-allow-origin', '*'); res.setHeader('cache-control', 'no-store'); res.end(JSON.stringify(DOC)); };
