// ORA · openapi.json — catalogo de licenciamento 0001sensations (v2.3)
// ORA 22/07/2026: obra deixa de ser required (nunca era exigido antes do 402
// no codigo real); cada operacao ganha security:[{x402:[]}] formal +
// components.securitySchemes.x402 — para provers como o x402scan reconhecerem
// o esquema standard em vez de depender só da extensao informal x-payment-info.
// ORA 31/07/2026: documentado GET /hashes (snapshot de integridade das obras,
// gratuito, sem x402) - deriva de v_integridade_obras, mesma fonte que /integridade.
const GATEWAY = 'https://ora-x402-gateway.vercel.app';
function xPaymentHeaderParam() { return { name: 'X-PAYMENT', in: 'header', required: false, description: 'Prova de pagamento x402.', schema: { type: 'string', minLength: 8 } }; }
function obraParam() { return { name: 'obra', in: 'query', required: false, description: 'Titulo ou ID da obra 0001sensations a licenciar.', schema: { type: 'string', minLength: 1, maxLength: 200, default: 'presenca', examples: ['presenca', 'valium'] }, example: 'presenca' }; }
function resp402(desc) { return { description: desc, headers: { 'PAYMENT-REQUIRED': { description: 'PaymentRequired canonico x402 v2 (JSON base64).', schema: { type: 'string' } } }, content: { 'application/json': { schema: { type: 'object', properties: { x402Version: { type: 'integer' }, error: { type: 'string' }, accepts: { type: 'array', items: { type: 'object' } } } } } } }; }
function resp200() { return { description: 'Licenca emitida', content: { 'application/json': { schema: { type: 'object', required: ['acesso', 'licenca'], properties: { acesso: { type: 'string' }, licenca: { type: 'object' } } } } } }; }
function op(id, summary, priceUsd, withObra) { const o = { operationId: id, summary, tags: ['Licenciamento'], security: [{ x402: [] }], 'x-payment-info': { price: { mode: 'fixed', currency: 'USD', amount: priceUsd }, protocols: [{ x402: {} }] }, responses: { '200': resp200(), '402': resp402('Payment Required.') } }; if (withObra) o.parameters = [obraParam()]; return { get: o }; }
function respHashes() { return { description: 'Snapshot da integridade das 65 obras tokenizadas (0001sensations, Agosto 2021). Fonte unica: v_integridade_obras. Mesma verdade que /integridade mostra a humanos, aqui em JSON para agentes.', content: { 'application/json': { schema: { type: 'object', required: ['version', 'generated_at', 'source', 'collection', 'works'], properties: { version: { type: 'string' }, generated_at: { type: 'string', format: 'date-time' }, source: { type: 'string' }, collection: { type: 'object', properties: { name: { type: 'string' }, total: { type: 'integer' }, preservadas: { type: 'integer' }, perdidas: { type: 'integer' } } }, works: { type: 'array', items: { type: 'object', properties: { tokenId: { type: 'integer' }, estado: { type: 'string', enum: ['preservada', 'perdida'] }, imageCid: { type: 'string', nullable: true }, metadataCid: { type: 'string', nullable: true }, sha256: { type: 'string', nullable: true }, bytes: { type: 'integer', nullable: true }, arcaEm: { type: 'string', format: 'date-time', nullable: true } } } } } }, example: { version: '1.0', generated_at: '2026-07-31T06:55:15.820Z', source: 'v_integridade_obras', collection: { name: '0001sensations', total: 65, preservadas: 52, perdidas: 13 }, works: [ { tokenId: 3, estado: 'preservada', imageCid: 'QmZq4AddUJDCbYX4pH1uJ2UPgS6tayCCq9G3JD8pEJd8GH', metadataCid: 'QmeyAiE2zrhEbSaDen5nBKNuEWag823TRbqixthr8t9EhG', sha256: '8fb14a89b52de1754fc09e2a4d72c54be586e0a36e656c22d3a4442153b073b9', bytes: 3208681, arcaEm: '2026-07-25T10:46:29.645+00:00' }, { tokenId: 2, estado: 'perdida', imageCid: null, metadataCid: null, sha256: null, bytes: null, arcaEm: null } ] } } } }; }
function opHashes() { return { get: { operationId: 'getHashes', summary: 'Snapshot da integridade das obras preservadas', tags: ['Integridade'], responses: { '200': respHashes() } } }; }
const DOC = { openapi: '3.1.0', info: { title: '0001sensations · Licenciamento de Arte via x402', version: '2.3.0', description: 'Licenciamento directo de obras originais 0001sensations.', contact: { email: 'jasm43@gmail.com' } }, servers: [{ url: GATEWAY }], components: { securitySchemes: { x402: { type: 'apiKey', name: 'X-PAYMENT', in: 'header', description: 'Prova de pagamento x402 (protocolo HTTP 402 Payment Required). Ver PAYMENT-REQUIRED na resposta 402 para os detalhes de como pagar.' } } }, paths: { '/licenca/preview': op('getLicencaPreview', '0001sensations · Licenca Preview', '1.618', true), '/licenca/editorial': op('getLicencaEditorial', '0001sensations · Licenca Editorial', '16.18', true), '/licenca/treino': op('getLicencaTreino', '0001sensations · Licenca de Treino IA', '161.80', true), '/licenca/arquivo': op('getLicencaArquivo', '0001sensations · Arquivo completo', '10000.00', true), '/hashes': opHashes() } };
module.exports = (req, res) => { res.setHeader('content-type', 'application/json; charset=utf-8'); res.setHeader('access-control-allow-origin', '*'); res.setHeader('cache-control', 'no-store'); res.end(JSON.stringify(DOC)); };
